// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmhmmcgyalohnjffpqkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtaG1tY2d5YWxvaG5qZmZwcWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTg2NzEsImV4cCI6MjA3MzU5NDY3MX0.Es0J0hmokjxM1d5f_MTAvCVrE7RR0FJXRjqgik347-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});